apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-2019
  labels:
    app: blog-2019
spec:
  replicas: 1
  template:
    metadata:
      name: blog-2019
      labels:
        app: blog-2019
    spec:
      containers:
      - name: blog
        image: michmike/blogngn:v1
        resources:
          limits:
            memory: "700Mi"
          requests:
            memory: "400Mi"
        ports:
             - containerPort: 80
      tolerations:
      - key: "windows"
        value: "2019"
  selector:
    matchLabels:
      app: blog-2019
---
apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: blog-2019
