apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-2019
  labels:
    app: blog-2019
spec:
  replicas: 1
  template:
     metadata:
      name: blog-2019
      labels:
          app: blog-2019
      spec:
      containers:
      - name: blog
        Image: demo.goharbor.io/vmworld/blogengineui:v4
        resources:
               limits:
                   cpu: 1
                   memory: "800Mi"
              requests:
                    cpu: .1
                    memory: "300Mi"
        ports:
             - containerPort: 80
        nodeSelector:
        "beta.kubernetes.io/os": windows
  selector:
    matchLabels:
      app: blog-2019
---
apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: blog-2019
