apiVersion: v1
kind: Pod
metadata:
  name: blogng  
spec:
  containers:
  - name: blogng
    image: michmike/blogengineui:v4
    resources:
      limits:
        memory: "800Mi"
      requests:
        memory: "300Mi"
