apiVersion: v1
kind: Pod
metadata:
  name: iis-1903
  labels:
    app: iis-1903
spec:
  containers:
  - name: iis
    image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
    resources:
      limits:
        memory: "700Mi"
      requests:
        memory: "400Mi"
    ports:
    - containerPort: 80
  tolerations:
  - key: "windows"
    value: "2019"
---
apiVersion: v1
kind: Service
metadata:
  name: iis
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: iis-1903
