apiVersion: v1
kind: Pod
metadata:
  name: oldwebapp
  labels:
    app: oldwebapp
spec:
  containers:
  - name: oldwebapp
    image: chrisumbel/oldwebapp:latest
    ports:
    - containerPort: 80
  tolerations:
  - key: "windows"
    value: "2019"
---
apiVersion: v1
kind: Service
metadata:
  name: oldwebapp
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: oldwebapp
